Table car {
    id              uuid        [primary key]
    brand           varchar
    model           varchar
    year_of_release integer
    cost            integer
    post_posted     timestamp
    post_updated    timestamp
}